esphome:
  on_boot:
    priority: -100
    then:
      - if:
          condition:
            lambda: "return !id(g_vs_color_initialized);"
          then:
            - globals.set:
                id: g_vs_color_initialized
                value: "true"
            - light.turn_on:
                id: vs_on_light
                red: 0%
                green: 20%
                blue: 60%
                brightness: 20%
            - light.turn_on:
                id: vs_off_light
                red: 100%
                green: 100%
                blue: 100%
                brightness: 11%

output:
  - platform: template
    id: vs_on_red_out
    type: float
    write_action:
      - lambda: return;

  - platform: template
    id: vs_on_green_out
    type: float
    write_action:
      - lambda: return;

  - platform: template
    id: vs_on_blue_out
    type: float
    write_action:
      - lambda: return;

  - platform: template
    id: vs_off_red_out
    type: float
    write_action:
      - lambda: return;

  - platform: template
    id: vs_off_green_out
    type: float
    write_action:
      - lambda: return;

  - platform: template
    id: vs_off_blue_out
    type: float
    write_action:
      - lambda: return;

light:
  - platform: rgb
    name: "Virtual Switch On Color"
    id: vs_on_light
    red: vs_on_red_out
    green: vs_on_green_out
    blue: vs_on_blue_out
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 0ms

  - platform: rgb
    name: "Virtual Switch Off Color"
    id: vs_off_light
    red: vs_off_red_out
    green: vs_off_green_out
    blue: vs_off_blue_out
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 0ms

binary_sensor:
  - id: !extend bs_button_1_click_event
    on_press:
      then:
        - if:
            condition:
              lambda: "return ${gang_count} >= 1;"
            then:
              - switch.toggle: virtual_switch_1

  - id: !extend bs_button_2_click_event
    on_press:
      then:
        - if:
            condition:
              lambda: "return ${gang_count} >= 2;"
            then:
              - switch.toggle: virtual_switch_2

  - id: !extend bs_button_3_click_event
    on_press:
      then:
        - if:
            condition:
              lambda: "return ${gang_count} >= 3;"
            then:
              - switch.toggle: virtual_switch_3

  - id: !extend bs_button_4_click_event
    on_press:
      then:
        - if:
            condition:
              lambda: "return ${gang_count} >= 4;"
            then:
              - switch.toggle: virtual_switch_4

globals:
  - id: g_vs_color_initialized
    type: bool
    restore_value: true
    initial_value: "false"

  - id: virtual_state_1
    type: bool
    restore_value: true
    initial_value: "false"
  - id: virtual_state_2
    type: bool
    restore_value: true
    initial_value: "false"
  - id: virtual_state_3
    type: bool
    restore_value: true
    initial_value: "false"
  - id: virtual_state_4
    type: bool
    restore_value: true
    initial_value: "false"

switch:
  - platform: template
    name: "Virtual Switch 1"
    id: virtual_switch_1
    internal: ${gang_count < 1}
    lambda: "return id(virtual_state_1);"
    turn_on_action:
      - globals.set:
          id: virtual_state_1
          value: "true"
      - lambda: |-
          auto cv = id(vs_on_light).remote_values;
          float r = cv.get_red();
          float g = cv.get_green();
          float b = cv.get_blue();
          float bri = cv.get_brightness();
          if (0 < id(gb_lights_1).size()) {
            auto call = id(gb_lights_1)[0]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }
          if (0 < id(gb_lights_2).size()) {
            auto call = id(gb_lights_2)[0]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }
    turn_off_action:
      - globals.set:
          id: virtual_state_1
          value: "false"
      - lambda: |-
          auto cv = id(vs_off_light).remote_values;
          float r = cv.get_red();
          float g = cv.get_green();
          float b = cv.get_blue();
          float bri = cv.get_brightness();
          if (0 < id(gb_lights_1).size()) {
            auto call = id(gb_lights_1)[0]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }
          if (0 < id(gb_lights_2).size()) {
            auto call = id(gb_lights_2)[0]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }

  - platform: template
    name: "Virtual Switch 2"
    id: virtual_switch_2
    internal: ${gang_count < 2}
    lambda: "return id(virtual_state_2);"
    turn_on_action:
      - globals.set:
          id: virtual_state_2
          value: "true"
      - lambda: |-
          auto cv = id(vs_on_light).remote_values;
          float r = cv.get_red();
          float g = cv.get_green();
          float b = cv.get_blue();
          float bri = cv.get_brightness();
          if (1 < id(gb_lights_1).size()) {
            auto call = id(gb_lights_1)[1]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }
          if (1 < id(gb_lights_2).size()) {
            auto call = id(gb_lights_2)[1]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }
    turn_off_action:
      - globals.set:
          id: virtual_state_2
          value: "false"
      - lambda: |-
          auto cv = id(vs_off_light).remote_values;
          float r = cv.get_red();
          float g = cv.get_green();
          float b = cv.get_blue();
          float bri = cv.get_brightness();
          if (1 < id(gb_lights_1).size()) {
            auto call = id(gb_lights_1)[1]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }
          if (1 < id(gb_lights_2).size()) {
            auto call = id(gb_lights_2)[1]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }

  - platform: template
    name: "Virtual Switch 3"
    id: virtual_switch_3
    internal: ${gang_count < 3}
    lambda: "return id(virtual_state_3);"
    turn_on_action:
      - globals.set:
          id: virtual_state_3
          value: "true"
      - lambda: |-
          auto cv = id(vs_on_light).remote_values;
          float r = cv.get_red();
          float g = cv.get_green();
          float b = cv.get_blue();
          float bri = cv.get_brightness();
          if (2 < id(gb_lights_1).size()) {
            auto call = id(gb_lights_1)[2]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }
          if (2 < id(gb_lights_2).size()) {
            auto call = id(gb_lights_2)[2]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }
    turn_off_action:
      - globals.set:
          id: virtual_state_3
          value: "false"
      - lambda: |-
          auto cv = id(vs_off_light).remote_values;
          float r = cv.get_red();
          float g = cv.get_green();
          float b = cv.get_blue();
          float bri = cv.get_brightness();
          if (2 < id(gb_lights_1).size()) {
            auto call = id(gb_lights_1)[2]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }
          if (2 < id(gb_lights_2).size()) {
            auto call = id(gb_lights_2)[2]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }

  - platform: template
    name: "Virtual Switch 4"
    id: virtual_switch_4
    internal: ${gang_count < 4}
    lambda: "return id(virtual_state_4);"
    turn_on_action:
      - globals.set:
          id: virtual_state_4
          value: "true"
      - lambda: |-
          auto cv = id(vs_on_light).remote_values;
          float r = cv.get_red();
          float g = cv.get_green();
          float b = cv.get_blue();
          float bri = cv.get_brightness();
          if (3 < id(gb_lights_1).size()) {
            auto call = id(gb_lights_1)[3]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }
          if (3 < id(gb_lights_2).size()) {
            auto call = id(gb_lights_2)[3]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }
    turn_off_action:
      - globals.set:
          id: virtual_state_4
          value: "false"
      - lambda: |-
          auto cv = id(vs_off_light).remote_values;
          float r = cv.get_red();
          float g = cv.get_green();
          float b = cv.get_blue();
          float bri = cv.get_brightness();
          if (3 < id(gb_lights_1).size()) {
            auto call = id(gb_lights_1)[3]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }
          if (3 < id(gb_lights_2).size()) {
            auto call = id(gb_lights_2)[3]->turn_on();
            call.set_rgb(r, g, b);
            call.set_brightness(bri);
            call.perform();
          }
